'use strict';
// The manifest and reference.html are generated by build.js from src/nyx.css,
// src/nyx.js and src/nyx.d.ts. These tests assert that what they claim is
// actually in the sources — a drifting manifest is worse than none.
const { describe, it, after } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');

const root = path.join(__dirname, '..');
const readSrc = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const manifest = JSON.parse(readSrc('dist/manifest.json'));
const css = readSrc('src/nyx.css');
const js = readSrc('src/nyx.js');
const pkg = require('../package.json');

describe('manifest.json — shape', () => {
  it('is stamped with the package version and its sources', () => {
    assert.equal(manifest.version, pkg.version);
    assert.deepEqual(manifest.sources, { css: 'src/nyx.css', js: 'src/nyx.js', types: 'src/nyx.d.ts' });
  });

  it('counts match the collections they describe', () => {
    for (const key of ['sections', 'components', 'classes', 'behaviours', 'attributes', 'events', 'api', 'tokens']) {
      assert.equal(manifest.counts[key], manifest[key].length, `counts.${key}`);
    }
  });

  // The assertions above only prove internal consistency: a build bug that drops half the
  // framework yields a smaller manifest that still agrees with itself. These floors are the
  // completeness half — raise them deliberately when the framework genuinely grows.
  it('meets the known-good floor for every collection', () => {
    const floor = { sections: 36, classes: 1270, behaviours: 44, attributes: 40, events: 51, api: 32, tokens: 49 };
    for (const [key, min] of Object.entries(floor)) {
      assert.ok(manifest.counts[key] >= min,
        `counts.${key} is ${manifest.counts[key]}, below the ${min} floor — the extractor lost something`);
    }
  });

  it('every section maps to an à-la-carte module file', () => {
    for (const s of manifest.sections) {
      assert.ok(s.module, `section "${s.title}" maps to no module — its CSS ships only in the bundle`);
      assert.ok(fs.existsSync(path.join(root, s.file)), `${s.file} does not exist`);
    }
    for (const c of manifest.classes) assert.ok(c.module, `${c.name} belongs to no module`);
  });

  it('has no duplicate names in any collection', () => {
    for (const key of ['classes', 'behaviours', 'attributes', 'events', 'api', 'tokens', 'components']) {
      const names = manifest[key].map((x) => x.name);
      assert.equal(new Set(names).size, names.length, `${key} contains duplicates`);
    }
  });
});

describe('manifest.json — every claim is in the source', () => {
  it('every class is a real selector in nyx.css', () => {
    for (const c of manifest.classes) {
      const selector = '.' + c.name.replace(':', '\\:');
      assert.ok(css.includes(selector), `${c.name} is not a selector in nyx.css`);
    }
  });

  it('every class points at the line it is defined on', () => {
    const lines = css.split('\n');
    for (const c of manifest.classes) {
      assert.ok(lines[c.line - 1].includes('nyx-'), `${c.name} line ${c.line} does not look like a rule`);
    }
  });

  it('every class names a section that exists', () => {
    const titles = new Set(manifest.sections.map((s) => s.title).concat(['BASE']));
    for (const c of manifest.classes) assert.ok(titles.has(c.section), `${c.name} → unknown section ${c.section}`);
  });

  it('a class only lists tokens that :root actually defines', () => {
    const defined = new Set(manifest.tokens.map((t) => t.cssVar));
    for (const c of manifest.classes) {
      for (const t of c.tokens) assert.ok(defined.has(t), `${c.name} lists ${t} as a token, but nothing defines it`);
    }
  });

  it('element-local custom properties are separated from design tokens', () => {
    const defined = new Set(manifest.tokens.map((t) => t.cssVar));
    const withCustom = manifest.classes.filter((c) => c.custom);
    assert.ok(withCustom.length, 'expected at least one class with a caller-set custom property');
    for (const c of withCustom) {
      for (const v of c.custom) {
        assert.ok(!defined.has(v), `${c.name}: ${v} is a design token, not a local property`);
        assert.ok(css.includes(v), `${c.name}: ${v} is not referenced in nyx.css`);
      }
    }
  });

  it('every behaviour maps to an init function that exists', () => {
    for (const b of manifest.behaviours) {
      assert.ok(js.includes(`function ${b.fn}(`), `${b.fn} missing from nyx.js`);
      assert.ok(js.split('\n')[b.line - 1].includes(b.fn), `${b.fn} line ${b.line} is wrong`);
    }
  });

  it('auto-init behaviours are the ones the INIT_STEPS registry lists', () => {
    // Assert the anchor exists before using it. Recomputing with the same fragile
    // lookup build.js uses would make this tautological: if the anchor ever moved,
    // both sides would go empty together and the test would still pass.
    const at = js.indexOf('const INIT_STEPS = [');
    assert.ok(at > 0, 'INIT_STEPS registry not found in src/nyx.js');
    const registry = js.slice(at, js.indexOf('\n  ];', at));
    for (const b of manifest.behaviours) {
      assert.equal(registry.includes(b.fn), b.auto, `${b.fn} auto flag is wrong`);
    }
    assert.ok(manifest.behaviours.filter((b) => b.auto).length >= 40, 'auto-init set collapsed');
  });

  it('every behaviour selector and class is real', () => {
    const known = new Set(manifest.classes.map((c) => c.name));
    for (const b of manifest.behaviours) {
      for (const s of b.selectors) assert.ok(js.includes(s), `${b.fn} claims selector ${s}`);
      for (const c of b.classes) assert.ok(known.has(c), `${b.fn} claims unknown class ${c}`);
    }
  });

  it('every event is dispatched by the runtime and traced to its source', () => {
    for (const e of manifest.events) {
      assert.ok(e.firedBy.length, `${e.name} has no source function`);
      const [, type, tail] = /^nyx:(\w+?)(-.*)$/.exec(e.name) || [, '', ''];
      // Overlay events are interpolated ('nyx:' + type + '-show'), so match either form.
      assert.ok(js.includes(`'${e.name}'`) || js.includes(`'${tail}'`), `${e.name} is never dispatched`);
    }
  });

  it('cancelable events are exactly the -before-* pair', () => {
    for (const e of manifest.events) {
      if (e.cancelable) assert.match(e.name, /-before-|^nyx:before-/, `${e.name} marked cancelable`);
    }
    const before = manifest.events.filter((e) => /-before-|^nyx:before-/.test(e.name));
    assert.ok(before.length && before.every((e) => e.cancelable), 'every -before-* event must be cancelable');
  });

  it('every attribute is read by the runtime', () => {
    for (const a of manifest.attributes) assert.ok(js.includes(a.name), `${a.name} unused`);
  });

  it('the API surface matches what the runtime returns', () => {
    const returned = js.slice(js.lastIndexOf('return {'));
    for (const m of manifest.api) {
      if (m.name === 'version') continue;
      assert.ok(new RegExp(`\\b${m.name}\\b`).test(returned), `Nyx.${m.name} is not returned by the runtime`);
      assert.ok(m.signatures.length, `Nyx.${m.name} has no signature`);
    }
  });

  it('sections list every class assigned to them, and only those', () => {
    for (const s of manifest.sections) {
      const expected = manifest.classes.filter((c) => c.section === s.title).map((c) => c.name);
      assert.deepEqual(s.classes, expected, s.title);
    }
  });
});

describe('reference.html — renders the manifest', () => {
  const html = readSrc('reference.html');
  const windows = [];
  after(() => { for (const w of windows) { try { w.close(); } catch { /* ignore */ } } });

  const open = (search) => {
    const dom = new JSDOM(html, { runScripts: 'dangerously', url: 'https://nyx.test/reference.html' + search, pretendToBeVisual: true });
    windows.push(dom.window);
    return dom.window.document;
  };

  it('inlines the same manifest that build.js wrote', () => {
    const doc = open('');
    const inlined = JSON.parse(doc.getElementById('nyx-manifest').textContent);
    assert.deepEqual(inlined.counts, manifest.counts);
    assert.equal(inlined.version, manifest.version);
  });

  it('renders rows and reports the total on first paint', () => {
    const doc = open('');
    const total = Object.values(manifest.counts).reduce((n, x) => n + x, 0) - manifest.counts.components;
    assert.match(doc.getElementById('status').textContent, new RegExp(`of ${total} matches`));
    assert.ok(doc.querySelectorAll('.ref-row').length > 0);
  });

  it('applies ?q= and ranks the exact name first', () => {
    const doc = open('?q=combobox');
    const names = [...doc.querySelectorAll('.ref-row h3')].map((h) => h.textContent.trim());
    assert.ok(names.includes('.nyx-combobox'), 'the class should be a hit');
    assert.equal(names[0], 'combobox', 'the behaviour is the most direct answer');
  });

  it('applies ?kind= to filter one collection', () => {
    const doc = open('?kind=behaviour');
    assert.equal(doc.querySelectorAll('.ref-row').length, manifest.counts.behaviours);
  });

  it('shows an empty state rather than a blank page', () => {
    const doc = open('?q=nosuchthinganywhere');
    assert.equal(doc.querySelectorAll('.ref-row').length, 0);
    assert.ok(doc.querySelector('.nyx-empty'), 'expected the nyx-empty placeholder');
  });

  it('escapes the manifest so it cannot break out of the JSON script tag', () => {
    const raw = html.slice(html.indexOf('id="nyx-manifest"'));
    const json = raw.slice(raw.indexOf('>') + 1, raw.indexOf('</script>'));
    assert.ok(!json.includes('<'), 'no raw "<" may sit inside the inlined JSON');
    assert.doesNotThrow(() => JSON.parse(json));
  });
});
